### ISSUE TITLE
.NET Core 3.1対応

### ISSUE THREAD

**Issue by Ovis** [SiroccoHub/OneWorldDbClient#7]
現行バージョンは.NET Core 2.2(.NET Standard 2.0)となっている。
.NET Core 3.1および Entity Framework Core 3.0 への更新が必要。

**Comment by arichika** [comment]
To use it with netcore app 3.1, change the dependencies while keeping netstandard 2.0.

**Comment by arichika** [comment]
https://github.com/SiroccoHub/OneWorldDbClient/tree/1.0.0
